import {
  Wifi,
  KeyRound,
  Car,
  PawPrint,
  CigaretteOff,
  Baby,
  Clock,
  MapPin,
  Phone,
  Sparkles,
  UtensilsCrossed,
  Landmark,
  Cross,
  PartyPopper,
  Copy,
  Bed,
  Bath,
  Users,
  type LucideIcon,
} from "lucide-react";

export const ICONS = {
  wifi: Wifi,
  key: KeyRound,
  parking: Car,
  pet: PawPrint,
  smoking: CigaretteOff,
  baby: Baby,
  clock: Clock,
  pin: MapPin,
  phone: Phone,
  sparkles: Sparkles,
  restaurant: UtensilsCrossed,
  attraction: Landmark,
  essential: Cross,
  events: PartyPopper,
  copy: Copy,
  bed: Bed,
  bath: Bath,
  guests: Users,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
